services:
  react:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.react

    image: react-runner
    container_name: react-dev

    stdin_open: true
    tty: true

    env_file:
      - .env

    volumes:
      - ./workspace:/workspace

    working_dir: /workspace

  dotnet:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dotnet

    image: dotnet-runner
    container_name: dotnet-dev

    stdin_open: true
    tty: true

    env_file:
      - .env

    volumes:
      - ./workspace:/workspace

    working_dir: /workspace

  specs:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.spec

    image: spec-builder
    container_name: spec-builder

    stdin_open: true
    tty: true

    volumes:
      - ./workspace:/workspace

    working_dir: /workspace
